Aljabar Matriks

- Berikan penjelasan tentang apa itu matriks
- Operasi Matriks

Buat Program untuk mengalikan matrik A dan B

m x n
n x k





# TIDAK MENGERJAKAN TETAP DILUAR

Tugas
 Operasi Matrik
- Penjumlahan, Perkalian, pengurangan, transpose Matrik
- Buat progam untuk mengalikan matrik A dan B
- TANPA "@"

In [ ]:
import numpy as np
import sympy as sy

In [5]:
import numpy as np
A = np.array([[1,6,2],[2,4,3],[3,1,4]])
B = np.array([[2,5,4],[4,1,3],[4,8,3]])
C = np.array([[3,6],[9,4],[9,3]])
D = np.array([[8,4,2],[3,1,6],[4,5,7]])
E = A+B
F = 2*A
G = A@C
H = B@C
I = A@H
J = A@B
K = J@C


print(A)
print('\n')
print(B)
print('\n')
print(C)
print('\n')
print(D)
print('\n')
print(E)
print('\n')
print(F)
print('\n')
print(G)
print('\n')
print(H)
print('\n')
print(I)
print('\n')
print(J)
print('\n')
print(K)
print('\n')

[[1 6 2]
 [2 4 3]
 [3 1 4]]


[[2 5 4]
 [4 1 3]
 [4 8 3]]


[[3 6]
 [9 4]
 [9 3]]


[[8 4 2]
 [3 1 6]
 [4 5 7]]


[[ 3 11  6]
 [ 6  5  6]
 [ 7  9  7]]


[[ 2 12  4]
 [ 4  8  6]
 [ 6  2  8]]


[[75 36]
 [69 37]
 [54 34]]


[[ 87  44]
 [ 48  37]
 [111  65]]


[[597 396]
 [699 431]
 [753 429]]


[[34 27 28]
 [32 38 29]
 [26 48 27]]


[[597 396]
 [699 431]
 [753 429]]




In [9]:
Ctrans=C.transpose()
Cova=Ctrans@C
Cova

array([[171,  81],
       [ 81,  61]])

In [10]:
Covb=C@Ctrans
Covb

array([[45, 51, 45],
       [51, 97, 93],
       [45, 93, 90]])